export const SUBMIT_MAIL_REQ = 'SUBMIT_MAIL_REQ'
export const SUBMIT_MAIL_OK = 'SUBMIT_MAIL_OK'
export const SUBMIT_MAIL_FAILED = 'SUBMIT_MAIL_FAILED'

export const SUBMIT_CODE_REQ = 'SUBMIT_CODE_REQ'
export const SUBMIT_CODE_OK = 'SUBMIT_CODE_OK'
export const SUBMIT_CODE_FAILED = 'SUBMIT_CODE_FAILED'

export const SUBMIT_PASSWORD_REQ = 'SUBMIT_PASSWORD_REQ'
export const SUBMIT_PASSWORD_OK = 'SUBMIT_PASSWORD_OK'
export const SUBMIT_PASSWORD_FAILED = 'SUBMIT_PASSWORD_FAILED'